name: Sass

on:
  push:
    branches:
      - dev

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: dev
            fetch-depth: 0
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.3
        with:
          source: assets/sass/style.scss
          destination: assets/css/style.css

      - name: Add and Commit changes to gh-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -f assets/css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
